main/urls.py
from django.conf.urls import url
from .  import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

schedule/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.SubjectsView.as_view(), name='subjects'),
    url(r'^table/download/(?P<hashcode>.+)/$', views.DownloadView.as_view(), name='download'),
    url(r'^table/(?P<hashcode>.+)$', views.TableView.as_view(), name='table'),
    url(r'^ajax/get_subjects', views.get_subjects, name="index"),
    url(r'^refresh_data', views.refresh),
]

schedule_match/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^$', include("main.urls", namespace="main")),
	# url(r'^bestmatch/', include("bestmatch.urls", namespace="bestmatch")),
	url(r'^schedule/', include("schedule.urls", namespace="schedule")),
    url(r'^admin/', admin.site.urls),
]

schedule/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json
import datetime

from django.db import models

from schedule_match import settings

class Counter(models.Model):
    clicks = models.IntegerField(default=0)

class Session(models.Model):
    hashcode = models.CharField(max_length=50)
    created = models.DateTimeField()
    courses = models.TextField()
    numOfTables = models.IntegerField(default=0)

    @staticmethod
    def create_session(hashcode, courses):
        session = Session()
        session.hashcode = hashcode
        session.created = datetime.datetime.now()
        session.set_courses(courses)

        return session
    
    def set_courses(self, courses):
        self.courses = json.dumps(courses)

    def get_courses(self):
        return json.loads(self.courses)
        
    def __str__(self):
        return self.hashcode


class School(models.Model):
    name = models.CharField(max_length=50)
    last_modified = models.CharField(max_length=50)

    def __str__(self):
        return "%s - %s" % (self.name, self.last_modified)


class Subject(models.Model):
    school = models.ForeignKey('School', on_delete=models.CASCADE)

    abbr = models.CharField(max_length=50, verbose_name=u'Course Abbr')
    title = models.CharField(max_length=50, verbose_name=u'Course Title')
    credits = models.FloatField(max_length=20, default=3.0, verbose_name=u'Cr(US)')

    def __str__(self):
        return self.abbr


class SubjectInstance(models.Model):
    subject = models.ForeignKey('Subject', on_delete=models.CASCADE)
    section = models.CharField(max_length=10)
    days = models.CharField(max_length=10)
    startTime = models.DateTimeField()
    endTime = models.DateTimeField()
    faculty = models.CharField(max_length=50)
    room = models.CharField(max_length=50)

    def get_time(self):
        return "%s-%s" % (self.startTime.strftime("%H:%M"), self.endTime.strftime("%H:%M"))


    def __str__(self):
        return "%s %s"% (self.subject.abbr, self.section)

schedule/forms.py
from django import forms

from .models import Subject


class SubjectsForm(forms.Form):

    sub_abbr_1 = forms.CharField()
    sub_title_1 = forms.CharField()
    sub_credits_1 = forms.CharField(required=False)

    sub_abbr_2 = forms.CharField(required=False)
    sub_title_2 = forms.CharField(required=False)
    sub_credits_2 = forms.CharField(required=False)

    sub_abbr_3 = forms.CharField(required=False)
    sub_title_3 = forms.CharField(required=False)
    sub_credits_3 = forms.CharField(required=False)

    sub_abbr_4 = forms.CharField(required=False)
    sub_title_4 = forms.CharField(required=False)
    sub_credits_4 = forms.CharField(required=False)

    sub_abbr_5 = forms.CharField(required=False)
    sub_title_5 = forms.CharField(required=False)
    sub_credits_5 = forms.CharField(required=False)

    sub_abbr_6 = forms.CharField(required=False)
    sub_title_6 = forms.CharField(required=False)
    sub_credits_6 = forms.CharField(required=False)

    def group1(self):
        return [self[name] for name in filter(lambda x: x.endswith('_1'), self.fields)]

    def group2(self):
        return [self[name] for name in filter(lambda x: x.endswith('_2'), self.fields)]
    
    def group3(self):   
        return [self[name] for name in filter(lambda x: x.endswith('_3'), self.fields)]        
    
    def group4(self):   
        return [self[name] for name in filter(lambda x: x.endswith('_4'), self.fields)]        
    
    def group5(self):   
        return [self[name] for name in filter(lambda x: x.endswith('_5'), self.fields)]        
        
    def group6(self):   
        return [self[name] for name in filter(lambda x: x.endswith('_6'), self.fields)]   


    def clean_sub_abbr_1(self):
        field = self.cleaned_data['sub_abbr_1']
        try:
            Subject.objects.get(abbr__iexact=field)
        except:
            raise forms.ValidationError("Subject 1 does not exist.")
    
        return field

    def clean_sub_abbr_2(self):
        field = self.cleaned_data['sub_abbr_2']
        if field:
            try:
                Subject.objects.get(abbr__iexact=field)
            except:
                raise forms.ValidationError("Subject 2 does not exist.")
        return field

    def clean_sub_abbr_3(self):
        field = self.cleaned_data['sub_abbr_3']
        if field:
            try:
                Subject.objects.get(abbr__iexact=field)
            except:
                raise forms.ValidationError("Subject 3 does not exist.")
        return field

    def clean_sub_abbr_4(self):
        field = self.cleaned_data['sub_abbr_4']
        if field:
            try:
                Subject.objects.get(abbr__iexact=field)
            except:
                raise forms.ValidationError("Subject 4 does not exist.")
        return field

    def clean_sub_abbr_5(self):
        field = self.cleaned_data['sub_abbr_5']
        if field:
            try:
                Subject.objects.get(abbr__iexact=field)
            except:
                raise forms.ValidationError("Subject 5 does not exist.")
        return field

    def clean_sub_abbr_6(self):
        field = self.cleaned_data['sub_abbr_6']
        if field:
            try:
                Subject.objects.get(abbr__iexact=field)
            except:
                raise forms.ValidationError("Subject 2 does not exist.")
        return field

schedule/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import random
import string 

from django.shortcuts import render, reverse
from django.http import Http404, HttpResponseRedirect, HttpResponse, JsonResponse
from django.views.generic.base import TemplateView

from .utils import generate, deleteTables, refresh_data
from .forms import SubjectsForm
from .models import School, Counter, Subject, Session
from schedule_match import settings


def index(request):
    return HttpResponse("Hello, World!")

class SubjectsView(TemplateView):
    template_name = 'schedule/index.html'

    def get(self, request, *args):
        form = SubjectsForm()
        deleteTables()
        # try:
        date = School.objects.get(name="SST").last_modified
        
        return render(request, self.template_name, {'form': form, 'date': date})

    def post(self, request):

        def gen_hashcode():
            return ''.join(random.choice(string.digits) for _ in range(8))

        data = request.POST
        form = SubjectsForm(data)

        if form.is_valid():
            courses = []
            for field in data:
                if field.startswith('sub_abbr'):
                    if data[field]: 
                        courses.append(data[field].upper())

            while True:
                hashcode = gen_hashcode()
                try: 
                    Session.objects.get(hashcode=hashcode)
                except:
                    newSession = Session.create_session(hashcode=hashcode, courses=courses)
                    newSession.save()
                    break

            return HttpResponseRedirect(
                    reverse('schedule:table',
                            kwargs={'hashcode': hashcode}))
        else:
            return render(request, self.template_name, {'form': form})
        

class TableView(TemplateView):
    template_name = 'schedule/table.html'

    def get(self, request, *args, **kwargs):
        try:
            counter = Counter.objects.get(pk=1)
            counter.clicks += 1
            counter.save()
        except:
            print "Counter is not working"

        hashcode = kwargs.get('hashcode')
        page = request.GET.get('page')
        try:
            session = Session.objects.get(hashcode=hashcode)
        except:
            return HttpResponse("Session expired.")
        courses = session.get_courses()
        print "HERE1"
        tables = generate(hashcode=hashcode, courses=courses)
        # tables = generate(hashcode=hashcode)
        print "HERE2"
        session = Session.objects.get(hashcode=hashcode)
        size = session.numOfTables
        data = {
            'tables': tables,
            'size': size,
            'hashcode': hashcode,
        }
        
        return render(request, self.template_name, data)

class DownloadView(TemplateView):

    def get(self, request, *args, **kwargs):
        hashcode = kwargs.get('hashcode')
        page = int(request.GET.get('page'))
        page -= 1
        
        filename = 'table_%s_%s.xlsx' % (hashcode, page)
        file_path = os.path.join(settings.TABLES_DIR, filename)

        if os.path.exists(file_path):
            with open(file_path, 'rb') as fh:
                response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
                response['Content-Disposition'] = 'inline; filename=%s' % os.path.basename(file_path)
                return response
        raise Http404


def get_subjects(request):
    data = {
        'subjects': [(x.abbr, x.title, x.credits) for x in Subject.objects.all()]
    }
    return JsonResponse(data)

def refresh(request):
    try:
        refresh_data()
    except:
        return HttpResponse("Error...");
    else:
        return HttpResponse("Data refreshed");

templates/schedule/base.html
{% load staticfiles%}

<!DOCTYPE html>
<html>
<head>
	<title>ScheduleMatch</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'schedule/css/base.css' %}"/>
	{% block styles %}
	{% endblock %}

	<!-- Fonts -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Droid+Serif">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Quicksand">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans">

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	
	{% block scripts %}
	{% endblock %}

</head>


<body>

  	<div class="logo">
  		<a href="/">
			<h2><span class="part1">Schedule</span><span class="glyphicon glyphicon-th"></span><span class="part2">Match</span></h2>
		</a>
	</div>


	{% block content %}	
	{% endblock %}	
</body>

{% block post-scripts %}
{% endblock %}


</html>

templates/schedule/index.html
{% extends 'schedule/base.html' %}
{% load staticfiles %}


{% block styles %}
	<link rel="stylesheet" type="text/css" href="{% static 'schedule/css/index.css' %}"/>
{% endblock %}

{% block scripts %}
    <!-- JQuery for autocomplete -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

	<script>
		$(document).ready(function() {
			for(i = 1; i <= 6; i++) {
				$('#id_sub_abbr_' + i).addClass("form-control");
				$('#id_sub_title_' + i).addClass("form-control");
				$('#id_sub_credits_' + i).addClass("form-control");

				$('#id_sub_abbr_' + i).addClass("abbr");
				$('#id_sub_title_' + i).addClass("title");

				id = '#id_sub_credits_' + i
				$(id).addClass("credits");
			}
		}); 
	</script>
{% endblock%}

{% block content %}

	<p class="titleText"> Choose subjects </p>

	<form action="" method="post">
		{% csrf_token %}
		<table>
		<tr>
			<th> Abbr </th>
			<th> Title </th>
			<th> Cr(US) </th>
		</tr>
		<tr>
			{% for field in form.group1 %}
				<td> {{ field }} </td>
			{% endfor %}
		</tr>
		<tr>
			{% for field in form.group2 %}
				<td> {{ field }} </td>
			{% endfor %}
		</tr>
		<tr>
			{% for field in form.group3 %}
				<td> {{ field }} </td>
			{% endfor %}
		</tr>
		<tr>
			{% for field in form.group4 %}
				<td> {{ field }} </td>
			{% endfor %}
		</tr>
		<tr>
			{% for field in form.group5 %}
				<td> {{ field }} </td>
			{% endfor %}
		</tr>
		<tr>
			{% for field in form.group6 %}
				<td> {{ field }} </td>
			{% endfor %}
		</tr>		
		
		</table>
		<table>
				{% for field in form %}
			<tr> <td>{{field.errors}} </td> </tr>
		{% endfor %}				
		</table>

		<center>
			<button type="submit"> Generate </button>
		</center>
	</form>
	<center><p> Data was modified: {{date}}</p></center>
	<div id="example1"></div>
{% endblock%}

{% block post-scripts %}
	<script>
		var abbrs = []
		var titles = []
		var credits = []

		$(function() {
			$.ajax({
				url: '/schedule/ajax/get_subjects/', 
				data: {}, 
				dataType: 'json',
				success: function(data) {
					if(data.subjects) {
						subjects = data["subjects"];

						for (sub in subjects) {
							abbrs.push(subjects[sub][0])
							titles.push(subjects[sub][1])
							credits.push(subjects[sub][2])
						}
						
						for(i = 1; i <= 6; i++) {
							$('#id_sub_abbr_' + i).autocomplete({
								source: abbrs,
								select: function(data, value) {
									id = data.target.id.slice(-1)									
									value = value.item.value
									ind = abbrs.indexOf(value);
									$('#id_sub_title_' + id).val(titles[ind]);
									$('#id_sub_credits_' + id).val(credits[ind]);
								},
							});

							$('#id_sub_title_' + i).autocomplete({
								source: titles,
								select: function(data, value) {
									id = data.target.id.slice(-1)									
									value = value.item.value
									ind = titles.indexOf(value);
									$('#id_sub_abbr_' + id).val(abbrs[ind]);
									$('#id_sub_credits_' + id).val(credits[ind]);
								},
								
							});
						}
                	}
				}
			});
		});

	</script>
{% endblock %}

templates/schedule/table.html
{% extends 'schedule/base.html' %}
{% load staticfiles %}

{% block styles %}
	<link rel="stylesheet" type="text/css" href="{% static 'schedule/css/table.css' %}">
{% endblock %}

{% block scripts %}
	<script>
		var schedules = [];
		var size = {{ size }};
		var hashcode = {{ hashcode }};
		$(function() {
			{% for table in tables %}
				var htmlTable = '<table>' +					
				'<tr>'									+
					'<th width="90px"> Abbr</th>'		+
					'<th width="250px"> Title</th>'		+
					'<th class="section"> S </th>'			+
					'<th class="credits"> Cr(US) </th>'	+
					'<th class="days"> Days </th>'		+
					'<th class="time"> Time </th>'		+
					'<th width="100px"> Faculty </th>'	+
					'<th width="100xp"> Room </th>'		+
				'</tr>';

				{% for inst in table %}
					htmlTable += "<tr>";
					htmlTable += "<td>{{ inst.subject.abbr }}</td>";
					htmlTable += "<td>{{ inst.subject.title }}</td>";
					htmlTable += "<td class='section'>{{ inst.section }}</td>";
					htmlTable += '<td class="credits">{{ inst.subject.credits }} </td>';
					htmlTable += '<td class="days">{{ inst.days }} </td>';
					htmlTable += '<td class="time">{{ inst.get_time }} </td>';
					htmlTable += "<td>{{ inst.faculty }}</td>";
					htmlTable += "<td>{{ inst.room }}</td>";
					htmlTable += "</tr>";
				{% endfor %}
				htmlTable += '<table>'
				schedules.push(htmlTable);
			{% endfor %}
		});
		$(document).ready(function() {
			$("#schedule").html(schedules[0]);
			$("#saveBtn").attr("href", "{% url 'schedule:download' hashcode %}?page=1");				
			
			$("#prevBtn").click(function() {
				page = parseInt($('#page').text());
				if(page > 1) {
					page -= 1;
					$('#page').text(page);
					$("#schedule").html(schedules[page-1]);
					$("#saveBtn").attr("href", "http://www.google.com/");
					$("#saveBtn").attr("href", "{% url 'schedule:download' hashcode %}?page=" + page);				
				}

				
			});

			$("#nextBtn").click(function() {
				page = parseInt($('#page').text());
				if(page < size) {
					page += 1;
					$('#page').text(page);
					$("#schedule").html(schedules[page-1]);
					$("#saveBtn").attr("href", "{% url 'schedule:download' hashcode %}?page=" + page);				
				}
			});

			$("#saveBtn").click(function() {
				page = parseInt($('#page').text()) - 1;
			});


		});
	</script>

{% endblock %}

{% block content %}

<ul class="pager">
	<p>Table: <span id="page">1</span> out of  {{size}}</p>
    <li><a id="prevBtn" class="pagerBtn">Previous</a></li>
    <li><a id="nextBtn" class="pagerBtn">Next</a></li>
</ul>

{% if size %}
<table id="schedule">
</table>
{% else %}
<center>
	<h3> Sorry, can't generate schedule with given subjects.</h3>
	 <h3>Try to remove some subjects</h3>
</center>
{% endif%}

<ul class="pager">
	<li><a href="" id="saveBtn"> Download </a></li>
</ul>


{% endblock %}